# Generated by Django 4.0.5 on 2022-07-04 01:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('artist_type', models.CharField(choices=[('culinary', 'culinary'), ('musician', 'musician'), ('performer', 'performer'), ('visual', 'visual'), ('writer', 'writer'), ('other', 'other')], default='visual', max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('alias', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.CharField(max_length=200)),
                ('biography', models.CharField(max_length=200)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('culinary', 'culinary'), ('musician', 'musician'), ('performer', 'performer'), ('visual', 'visual'), ('writer', 'writer'), ('other', 'other')], max_length=20)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.artist')),
            ],
        ),
    ]
