# Generated by Django 4.0.5 on 2022-07-04 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_gallery_description_gallery_name_alter_artist_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='biography',
            field=models.TextField(),
        ),
    ]
